hifrontendcafe/website

- next.config.js
This PR removes the rewrite of home to calendar so we can have a proper homepage.
> Remove rewrite

- src/components/Header/index.tsx
- src/components/MentorCard/index.tsx
- src/lib/api.ts
- src/lib/types.ts
- ﻿arregle el warning de la falta de un key en el map de los nav links
- ahora se renderiza un texto diciendo que el mentor no esta disponible si la propiedad de active es false o undefined
**IMPORTANTE:** no aceptar esta pull request antes de que todos los mentores contengan un valor booleano en su documento de sanity de lo contrario todos los que no dispongan de esto saldran como no disponible
> feat: added disabled button if the mentor is not active

- src/components/CMYKCarousel/index.tsx
- src/components/CMYKItem/index.tsx
- src/components/CMYKItem/styles.module.css
- src/components/Header/index.tsx
- feat: added new carousel in the cmyk page
- feat: better responsive
- refactor: changes in the carousel from feedback
> changes in the carousel from feedback

- src/components/Footer/index.tsx
Modified color, links, layout and icons.
> Footer update

- src/lib/api.ts
- src/lib/queries.ts
- src/lib/querys.ts
- src/lib/types.ts
- src/pages/api/add-participant.ts
- src/pages/cmyk/index.tsx
- src/pages/docs/[slug].tsx
- src/pages/docs/index.tsx
- src/pages/eventos.tsx
- src/pages/mentorias/index.tsx
- src/pages/posts/[slug].tsx
- src/pages/posts/index.tsx
- src/pages/reactivistas/index.tsx
List of React groups (only the groups with 'approved' status will render) + CTA to add new participant.
FYI: I added two new groups for testing -> TestGroup and TestGroup#2, please remove them.
> reactGroups list + CTA addParticipant

- src/pages/reactivistas/index.tsx
> fix responsive view for reactivistas section

- src/lib/api.ts
- src/lib/queries.ts
- src/pages/ingles/index.tsx
Update of the main layout according to the latest design:
> feat: Apply updated english section layout design

- src/components/AboutSection/index.tsx
> Discord widget mobile view repaired

- src/components/Header/index.tsx
> Navigation fixed

- src/components/CMYKItemCard/index.tsx
- src/pages/cmyk/index.tsx
- yarn.lock
> Mini scroll fix

- src/_profiles/giancarlo-brusca.md
> feat(giancarlo-brusca): add new profile to the web

- src/components/AboutSection/index.tsx
- src/components/FeaturedCard/index.tsx
- src/components/MediaFeed/index.tsx
- src/components/ProfileCard/index.tsx
- src/pages/index.tsx
- src/pages/perfiles/index.tsx
- src/styles/index.css
changed bg color on about us section, mediafeed title, and fixed padding on cards
> home update

- src/components/ProfileCard/index.tsx
- src/pages/perfiles/index.tsx
Fix alignment of the main profiles card list
> fix(perfiles): profiles cards layout alignment and margins

- src/pages/docs/[slug].tsx
- src/pages/docs/index.tsx
> fix(#159): Remove hero from docs pages

- src/components/ProfileCard/index.tsx
- src/pages/perfiles/index.tsx
add green ring to profile photo
add large shadow to card
remove bottom border of card
make Title of index similar to other page titles
> fix(perfiles): improve profile styles

- src/components/CMYKItemCard/index.tsx
- src/pages/cmyk/index.tsx
> Cmyk changes

- src/pages/reactivistas/index.tsx
> Feat: add hero to Reactivistas

- src/components/reactivistas/CreateGroupForm/index.tsx
- src/pages/reactivistas/index.tsx
Changed hero text, padddings, bg-color on form, and some small styling details
> fix: Reactivistas

- src/components/StaffCard/index.tsx
- src/lib/api.ts
- src/lib/queries.ts
- src/lib/types.ts
- src/pages/equipo/index.tsx
> feature: fecTeam staff component

- public/img/location.svg
- src/components/ProfileCard/index.tsx
- src/lib/types.ts
- src/pages/api/google-sheet.ts
Add country of residence to the profile cards.
> feat(comunidad): add country of residence to the profile cards

- src/components/reactivistas/AddParticipantForm/index.tsx
- src/components/reactivistas/CreateGroupForm/index.tsx
- src/pages/reactivistas/index.tsx
> fix(reactivistas): fix padding and other small tweaks

- src/components/ProfileCard/index.tsx
- src/pages/api/google-sheet.ts
- src/pages/comunidad/index.tsx
Functionalities:
- Profiles can be filtered from a parameter in the url.
- Profiles can be filtered by clicking on a badge of a profile.
- If the technology doesn't exist, user will be redirected to the base url.
> add Profiles filter by query params

- src/components/Header/index.tsx
> fix(navbar): change style when route is active

- src/pages/equipo/index.tsx
> delete emoji from title

- src/components/ProfileCard/index.tsx
> fix: profile card grid width

- src/components/reactivistas/CreateGroupForm/index.tsx
> fix(reactivistas): fix input placeholder text color

- src/components/Hero/index.tsx
- src/components/reactivistas/CreateGroupForm/index.tsx
- src/pages/reactivistas/index.tsx
Reverts hifrontendcafe/website#191
> Revert "Updtate hero's numbers"

- src/components/Hero/index.tsx
> Update hero members number

- src/components/Hero/index.tsx
> Update projects and messages hero number

- src/components/Modal/index.tsx
- src/components/reactivistas/GroupRequirementsModal/index.tsx
> fix: mobile modal

- src/components/EventPreview/index.tsx
- src/components/Footer/index.tsx
New routes to footer
Mobile: 
Desktop:
-----------------------------------------------------------------------------------------------------------------------------------------
Added clarification that events are in local time:
> chore: add new routes to footer

- src/components/EventPreview/index.tsx
- src/components/Footer/index.tsx
> fix: footer with 3 grid column view

- src/components/MentorList/index.tsx
This reverts commit 917e68a1e85fa5642bd3a45010cd9e6e564183fa.
> Revert "Update index.tsx (#209)"

- src/components/EventPreview/index.tsx
> fix: change date format

- src/pages/comunidad/index.tsx
> feat: new filters and header redesign

- src/components/MentorCard/index.tsx
- src/components/MentorList/index.tsx
- src/components/Navbar/UserSettings.tsx
- src/components/Reactivistas/CreateGroupForm/index.tsx
- src/pages/comunidad/nuevo.tsx
- src/pages/inscripcion-cmyk/index.tsx
> refactor: improved performance at mentorias page

- src/components/MentorCard/index.tsx
* Remove capitalize class to fix a typo
> refactor: MentorCard add placeholder and blurDataURL

- src/components/ProfilesFilterForm/index.tsx
Automatically search for `AVAILABLE` people when the URLParam `?activos` is on.
> 'Activos' query param

- src/components/Header/index.tsx
- src/components/Layout/index.tsx
- Change sticky by fixed position in `header` of `Header` component
- Add padding top in `.container` of `Layout` component
No refactor was necessary! 👀
> Fix Navbar

- src/lib/completeTimezones.json
- src/lib/prisma-queries.ts
- src/lib/types.ts
- src/pages/perfiles/[slug].js
- src/pages/perfiles/[slug].tsx
- Added page by each user profile with discordId: `/perfiles/336692247649189891` (my discordId).
- Add query function to Prisma, interface and some style to view some user info
> Share profile

- src/pages/reactivistas/index.tsx
Para poder iterar mejor sobre reactivistas es mejor tener una feature flag que permita habilitar y deshabilitar la función.
Se usa la variable de entorno `REACTIVISTAS_ENABLED` para esa función
> Add feature flag for reactivistas page

- src/pages/_app.tsx
> Make hotjar env variables public

- src/components/FecHead/index.tsx
- src/components/Layout/index.tsx
- src/lib/api.ts
- src/lib/queries.ts
- src/lib/types.ts
- src/pages/cmyk/index.tsx
- src/pages/equipo/index.tsx
- src/pages/eventos.tsx
- src/pages/ingles/index.tsx
- src/pages/mentorias/index.tsx
- src/pages/reactivistas/index.tsx
- src/pages/talentos/index.tsx
> add get pages content from sanity #CU-1xpwq7v

- src/components/Header/index.tsx
- src/components/Navbar/index.tsx
- src/lib/queries.ts
- src/lib/types.ts
> add get navbar content from sanity #CU-1xpwr1f

- src/components/Footer/index.tsx
- src/lib/queries.ts
- src/lib/types.ts
#{CU-257cx15}
Add get footer nav content from sanity
> add footer nav content from sanity #CU-257cx15

- src/components/Steps/index.tsx
- src/lib/queries.ts
- src/lib/types.ts
- src/pages/mentorias/index.tsx
CU-1w988ex
- changed type of page adding the step array in `steps` field
- created component for steps called `Steps` and removed `MentorshipsSteps` 
- changed query of get pages by hero
> feat: steps by sanity

- src/components/Card/index.tsx
- src/components/EventPreview/index.tsx
> style: add text-informational to links

- src/components/MDX/index.tsx
{#25k0akc}
With this change the docs are nicer to read.
> style: font size and aligning of titles and paragraphs

- src/components/FecHead/index.tsx
- tailwind.config.js
> change font to rubik

- src/components/MediaFeed/index.tsx
> fix: add border to quoted tweets

- src/components/Profiles/index.tsx
> fix: scroll behavior in talentos page

- src/lib/api.ts
- src/pages/eventos.tsx
#{CU-2qv1v4j}
Modify import discord events as drafts
> modify import discord events as drafts

- src/lib/api.ts
- src/lib/queries.ts
- fix: get only first element of eventSettings (is an array)
- refactor: improve error handling
> Fix import events

- src/lib/api.ts
- src/lib/queries.ts
- src/lib/types.ts
#{CU-2r6m952}
Add tags on import discord events
> add tags on import discord events

- src/components/Hero/index.tsx
- src/lib/queries.ts
- src/lib/types.ts
- src/pages/index.tsx
- src/pages/posts/[slug].tsx
- src/pages/posts/index.tsx
> feat: get hero texts from sanity

- src/pages/cmyk/index.tsx
> feat: edition query param and links for editions

- src/components/MentorCard/index.tsx
- src/components/MentorList/index.tsx
- src/components/MentorList/useWarnings.tsx
- src/lib/calomentor.ts
Add validations for mentorships. 
- This add a warnings and mentorships of the month validations to user that try to book a mentorship.
> Add warnings and mentorships validation

- src/components/MentorCard/index.tsx
- src/components/ToastNotification/ToastNotification.tsx
- src/lib/mentors.ts
This is a quick solution to have a individual link for mentors
> Add id hashmark for mentors

- src/components/CMYKParticipantForm/index.tsx
- src/pages/inscripcion-cmyk/index.tsx
> Disable participant form

- package.json
- pnpm-lock.yaml
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/styles/index.css
- tailwind.config.js
Usa @next/font para mejorar la performance de carga de las fuentes
https://nextjs.org/docs/basic-features/font-optimization
> performance(fonts): use @next/font

- src/components/Navbar/NavItem.tsx
Simplifica el navbar haciendo uso del nuevo componente Link https://nextjs.org/docs/upgrading#link-component, además como nunca el navbar renderiza un botón había código innecesario que fue removido
La lógica para marcar el link activo tenía un bug, ahora debería funcionar correctamente, además se ajustaron las clases para adecuarse al figma
> fix(components/Navbar): simplify navbar, highlight active link

- src/pages/docs/[slug].tsx
- src/pages/docs/index.tsx
- src/pages/equipo/index.tsx
- src/pages/index.tsx
- src/pages/mentorias/feedback.tsx
- src/pages/mentorias/index.tsx
- src/pages/perfiles/[slug].tsx
- src/pages/posts/[slug].tsx
- src/pages/posts/index.tsx
- src/pages/talentos/index.tsx
- src/pages/talentos/nuevo.tsx
- src/pages/unauthorized/index.tsx
La idea general es usar mejor las cachés, no es necesario generar las páginas cada 1 segundo, si esto va a mejorar o no el tiempo al primer byte no lo sé, es un experimento
> performance(ttfb): try to improve ttfb adding more time before revalidating each page

- package.json
- pnpm-lock.yaml
- src/components/Analytics/index.tsx
- src/pages/_app.tsx
> feat: add vercel analytics component

- .storybook/main.js
- package.json
- pnpm-lock.yaml
- Install and setup [`@storybook/addon-postcss`](https://storybook.js.org/addons/@storybook/addon-postcss)
> Fix storybook startup

- src/components/FeaturedCard/index.tsx
- src/components/FeaturedCardList/index.tsx
- src/components/Page/Components.tsx
> refactor:  add native next/link

- src/app/eventos/components/UpcomingEvents.tsx
- src/components/DateWidget/index.stories.ts
- src/components/DateWidget/index.tsx
- src/components/EventList/index.tsx
- src/lib/formatDateTime.ts
- src/styles/index.css
Re-design de la sección "Próximos eventos"
> feat: add upcoming events comp

- src/app/mentorias/page.tsx
- Randomize mentor list to avoid bias
> feat(mentors): randomize mentors

- README.md
- Replace HTML for Markdown syntax
- Add links to website and CMS
- Update/fix icons
- Restructured sections
> docs: update and add site links

- .github/workflows/deploy_storybook.yml
- Add Github Actions that deploy Storybook
> feat: setup storybook deployment

- src/schemas/mentor.ts
- src/schemas/person.ts
- Add social media fields on Sanity schemas (I forgot about this somehow).
> fix: add missing social media fields

- src/app/(website)/cmyk/layout.tsx
- src/app/(website)/cmyk/page.tsx
> fix: recover cmyk pages
